# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:54
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=1024, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_type', models.CharField(default='text/plain', max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.TextField(blank=True, max_length=1024, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('liked', models.BooleanField(default=False)),
                ('content_type', models.CharField(default='text/html', max_length=64)),
                ('search_vector_description', django.contrib.postgres.search.SearchVectorField(verbose_name=models.TextField(blank=True))),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.TagName'),
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
    ]
