# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 12:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_type',
            field=models.CharField(blank=True, default='text/x-markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, default=[], size=None),
        ),
    ]
